default: &default

  adapter: postgresql

  encoding: unicode

  host: db

  username: SperDocs

  password: <%= ENV['SPERDOCS_DATABASE_PASSWORD'] %>

  pool: 5



development:

  <<: *default

  database: SperDocs_development





test:

  <<: *default

  database: SperDocs_test


